brew "colima"
brew "docker"
brew "docker-buildx"
brew "docker-compose"
brew "docker-credential-helper"
brew "lazygit"
brew "mise"
brew "neovim"

# Ruby
brew "gmp"
brew "libyaml"

vscode "editorconfig.editorconfig"
